FROM python:3.8.11-slim-buster

RUN apt update
RUN apt install -y gcc g++ \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

RUN pip install tfx==1.2.0 \
    tensorflow_decision_forests==0.1.8 \
    tensorflow==2.5.0\
    pydantic